version: "3.3"

services:
  mind_db:
    image: mindsdb/mindsdb:latest
    container_name: mind_db
    user: root
    ports:
      - "47338:47338"  
      - "47334:47334" 
    environment:
      MINDSDB_USERNAME: admin
      MINDSDB_PASSWORD: passwords
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: password
      AWS_ENDPOINT_URL: http://s3:9000
      BUCKET: mindmodel 
      AWS_S3_USE_SSL: false
      S3-SIGNATURE_VERSION: s3v4
      AWS_S3-USE_SIGV4: true
    networks:
      - mind_clik
    depends_on:
      - clickhouse
      - s3
    entrypoint: /entrypoint.sh  
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - db_mind:/root/mdb_storage
      - ./config.json:/root/mindsdb_config.json

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "18123:8123"  # HTTP interface
      - "19000:9000"  # Native TCP interface
    networks:
      - mind_clik
    environment:
      - CLICKHOUSE_PASSWORD=changeme
    volumes:
      - ch_data:/var/lib/clickhouse/
      - ch_logs:/var/log/clickhouse-server/

  s3:
      image: 'minio/minio:RELEASE.2024-12-18T13-15-44Z'
      container_name: s3
      ports:
        - '9000:9000'
        - '9001:9001'
      networks:
        - mind_clik    
      environment:
        MINIO_ROOT_USER: minio
        MINIO_ROOT_PASSWORD: password
      volumes:
        - mini:/data/minio
      command: server /data/minio --console-address ":9001"
volumes:
  db_mind:
  ch_data:
  ch_logs:
  mini:

networks:
  mind_clik:
#JTTgtTPdVidBKWe34oU8   nmLqPnOucgMKpJb8k2WkuOs7PFK6RT1xtizy8ge4
#pip install .[neuralforecast]
#--default-timeout=30000000